description = "GNU TLS library"
name = "libgnutls"

maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[[external]]
kind = "system"
[external.origin."case(distribution)"]
"..." = []
"debian|ubuntu" = ["libgnutls28-dev"]
