name = "gwindows"
version = "1.4"
description = "GWindows - Ada Framework for Windows Development"
authors = [
	"David Botton",
	"Gautier de Montmollin"
]
maintainers = [
	"Felix Patschkowski <felix.patschkowski@nexperia.com>"
]
maintainers-logins = [
	"patschkowski"
]
licenses = "LGPL-2.0-or-later"
project-files = [
	"gnatcom/gnatcom.gpr",
	"gnatcom/gnatcom_tools.gpr",
	"gwindows/gwindows.gpr"
]
executables = [
	"bindcom",
	"comscope",
	"createcom",
	"makeguid"
]

[available.'case(os)']
windows = true
'...' = false

[environment.PATH]
prepend = "${CRATE_ROOT}/alire/build/gnatcom/tools"

[origin]
commit = "2484efb9dea05b4025a8939bb9d2445de4553c46"
url = "git+https://github.com/zertovitch/gwindows.git"

