name = "lua"
version = "5.4.2"
description = "Lua - A Scripting Language"
maintainers = ["Felix Patschkowski <felix.patschkowski@nexperia.com>"]
maintainers-logins = ["Patschkowski"]
licenses = ["MIT"]
project-files = ["lua.gpr"]
executables = ["lua"]
[origin]
commit = "8ad492521f9c184ec8f8d900a86c8e5f97e635bf"
url = "git+https://github.com/Patschkowski/lua.git"

