name = "lua"
version = "5.4.2"
description = "Lua - A Scripting Language"
maintainers = ["Felix Patschkowski <felix.patschkowski@nexperia.com>"]
maintainers-logins = ["Patschkowski"]
licenses = ["MIT"]
project-files = ["lua.gpr"]
executables = ["lua"]

[environment]
PATH.prepend = "${CRATE_ROOT}/alire/build/bin"
[origin]
commit = "b96b41bb7fce470363ad7a427d148cdfac3fd87e"
url = "git+https://github.com/Patschkowski/lua.git"

